### ISSUE TITLE
not the same as in youtube

### ISSUE THREAD

**Issue by juha-h** [Jyodann/SpinnerJetpackCompose#1]
Looks like this project does not match the Youtube video https://www.youtube.com/watch?v=H8Fy4jqXfwg.  Do you have the code of Youtube video somewhere?

**Comment by Jyodann** [comment]
Hello, the commit fb149ac should fix the issue, do let me know if you need more assistance! Thank you for your continued support 😄

**Comment by juha-h** [comment]
Sorry, but the commit did not fix the issue.  The app in this project is very different from the one you describe in the Youtube video.

**Comment by Jyodann** [comment]
Hi there, the code in the video is located in [`MainActivity.kt`](https://github.com/Jyodann/SpinnerJetpackCompose/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fexample%2Fspinnerjetpackcompose%2FMainActivity.kt) 

The differences in code would mainly be from the upgrade from Material 2 to Material 3, but the core concepts remain the same. 

Do let me know if you encounter any more issues. 😊

**Comment by juha-h** [comment]
Jordan writes:

> Hi there, the code in the video is located in [`MainActivity.kt`](https://github.com/Jyodann/SpinnerJetpackCompose/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fexample%2Fspinnerjetpackcompose%2FMainActivity.kt) 

Thanks, it is now same as the Youtube one.

> The differences in code would mainly be from the upgrade from Material
> 2 to Material 3, but the core concepts remain the same. 
> 
> Do let me know if you encounter any more issues. 😊

Not really any issues.  Just wondering would it be somehow possible to
implement function

fun spinTo(val item: text)

or

fun spinTo(val itemIndex: Int)

that would cause spinner to spin to the item given as argument?

-- Juha
